- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: Include App Pre-clean tasks
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-clean

- name: Download App Content
  ansible.builtin.import_role:
    name: common
    tasks_from: app-download

- name: Copy Nginx Configuration
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Copy RoboSHop Nginx Configuration
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/nginx.conf

- name: Restart Nginx Service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes



