- name: Install Maven
  ansible.builtin.dnf:
    name: maven
    state: installed

- name: App Pre-Req
  ansible.builtin.import_tasks:
    file: app-prereq.yml

- name: Build Java Package
  ansible.builtin.shell: mvn clean package ; mv target/{{component}}-1.0.jar {{component}}.jar
  args:
    chdir: /app

- name: SystemD Setup
  ansible.builtin.import_tasks:
    file: systemd.yml

- name: Load Schema
  ansible.builtin.import_tasks:
    file: schema.yml
  when: is_schema_needed
