- name: Enable NodeJS
  ansible.builtin.shell: dnf module disable nodejs -y; dnf module enable nodejs:18 -y
  
- name: Install NodeJS
  ansible.builtin.dnf:
    name: nodejs
    state: installed
    
- name: App Pre-Req
  ansible.builtin.import_tasks:
    file: app-prereq.yml
    
- name: Install NodeJS Dependences
  ansible.builtin.shell: npm install
  args:
    chdir: /app
    
- name: SystemD Setup
  ansible.builtin.import_tasks:
    file: systemd.yml
    
- name: Load Schema
  ansible.builtin.import_tasks:
    file: mongo-schema.yml