- name: Install Python
  ansible.builtin.dnf:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: App Pre-Req
  ansible.builtin.import_tasks:
    file: app-prereq.yml

- name: Download Python Dependencies
  ansible.builtin.shell: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: SystemD Setup
  ansible.builtin.import_tasks:
    file: systemd.yml

- name: Load Schema
  ansible.builtin.import_tasks:
    file: schema.yml
  when: is_schema_needed
